ALTER TABLE Quest ADD COLUMN startdate DATE;
ALTER TABLE Quest ADD COLUMN enddate DATE;
ALTER TABLE Adventure ADD COLUMN startdate DATE;
ALTER TABLE Adventure ADD COLUMN enddate DATE;
ALTER TABLE Task ADD COLUMN startdate DATE;
ALTER TABLE Task ADD COLUMN enddate DATE;